Repository openshift/csi-driver-shared-resource, pull requests merged in 2025-07, with the labels that each got.

#380 Adding psrvere as reviewer and approver
  OWNERS
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#381 Minor fix in Pipelines
  .tekton/openshift-builds-shared-resource-webhook-pull-request.yaml
Labels: lgtm, qe-approved, docs-approved, px-approved

#388 Add Service Accounts and Update Go Tooltset Image
  .konflux/shared-resource-webhook/Dockerfile
  .konflux/shared-resource/Dockerfile
  .tekton/openshift-builds-shared-resource-pull-request.yaml
  .tekton/openshift-builds-shared-resource-push.yaml
  .tekton/openshift-builds-shared-resource-webhook-pull-request.yaml
  .tekton/openshift-builds-shared-resource-webhook-push.yaml
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#415 BUILD-1446: Rebase Builds 1.5 with Master
  .konflux/shared-resource-webhook/Dockerfile
  .konflux/shared-resource/Dockerfile
  .tekton/openshift-builds-shared-resource-pull-request.yaml
  .tekton/openshift-builds-shared-resource-push.yaml
  .tekton/openshift-builds-shared-resource-webhook-pull-request.yaml
  .tekton/openshift-builds-shared-resource-webhook-push.yaml
  OWNERS
Labels: lgtm, approved, qe-approved, docs-approved, px-approved, jira/valid-reference

#422 NO_JIRA: Add mount binary to base image
  .konflux/shared-resource-webhook/Dockerfile
  .konflux/shared-resource/Dockerfile
  .tekton/openshift-builds-shared-resource-pull-request.yaml
  .tekton/openshift-builds-shared-resource-push.yaml
  rpms.in.yaml
  rpms.lock.yaml
  ubi.repo
Labels: lgtm, approved, qe-approved, docs-approved, px-approved

#421 Cherry-pick: Add mount binary to base image
  .konflux/shared-resource-webhook/Dockerfile
  .konflux/shared-resource/Dockerfile
  .tekton/openshift-builds-shared-resource-pull-request.yaml
  .tekton/openshift-builds-shared-resource-push.yaml
  rpms.in.yaml
  rpms.lock.yaml
  ubi.repo
Labels: lgtm, approved, ok-to-test, qe-approved, docs-approved, px-approved
